### ISSUE TITLE
Conflict on post requests with both params and text

### ISSUE THREAD

**Issue by SaberStrat** [loadimpact/har-to-k6#14]
**How to reproduce:**
Run
```
fetch('http://example.com', {
      method: 'POST',
      headers: new Headers({
               'Content-Type': 'application/x-www-form-urlencoded'
               }),
		body: 'foo0=bar0&foo1=bar1'
    })
    .then(res => res.json())
    .then(console.log)
```
in Chrome v78.0.3904.97 DevTools Console and Save Content as HAR the Network Tab.
Trying to convert it using the har-to-k6 converter results in the error
```Post data conflict (0): specify 1 of params or text```

**Problem:**
Now, from how I understand the HAR 1.2 specification, a HAR postData entry should only contain *either* a non-empty `params` *or* `text`. And according to https://github.com/loadimpact/har-to-k6/blob/master/src/validate/postData.js#L54, the converter implemented that specification correctly. 

However, the Firefox and Chrome DevTools both export a POST request with an *application/x-www-form-urlencoded* encoded request body with parameters into a HAR entry with both `params` *and* `text`:
```
...
"postData": {
      "mimeType": "application/x-www-form-urlencoded",
      "text": "foo0=bar0&foo1=bar1",
      "params": [{
            "name": "foo0",
            "value": "bar0"
      },{
            "name": "foo1",
            "value": "bar1"
      }]
}
...
```

Since POST request bodies with parameters are fairly common, and Firefox and Chrome DevTools are probably fairly common tools to create HAR files, what's the appropriate way to use this converter on HAR files with POST bodies with parameters?

(Worst case, I'll have to prefix this converter with a script that sets the `text` element to an empty string for `postData`.)

**Comment by simskij** [comment]
In this case we need to give priority to one of the two. If both exists, should we prioritize:

🚀 Text, or
🥳 Params

If you prefer one or the other, feel free to vote with emojis. :)

**Comment by simskij** [comment]
An issue has been raised with the chromium team:
https://bugs.chromium.org/p/chromium/issues/detail?id=1049080

**Comment by simskij** [comment]
An issue has been raised the firefox team as well:
https://bugzilla.mozilla.org/show_bug.cgi?id=1613361

**Comment by MStoykov** [comment]
Maybe `har-to-k6` could urlencode the params to the text body and check if they match ... if so .. it doesn't matter if not I would think it should raise an error :). 

For the record, the current in k6 har converter does prefer the params as shown by [this](https://github.com/loadimpact/k6/blob/74f11a6b6703282c282c2baf42ccaa8fa3a23d31/converter/har/converter.go#L349-L358) and [this](https://github.com/loadimpact/k6/blob/74f11a6b6703282c282c2baf42ccaa8fa3a23d31/converter/har/converter.go#L407-L424) code, so I guess 🥳

**Comment by allansson** [comment]
We could check the mime-type to see if it is either `multipart/form-data` or `application/x-www-form-urlencode` and pick the correct properties based on that? 

Otherwise I would lean towards prioritizing `params` since they are provably parseable from `text`. Can't imagine a case where the `text` would not be equivalent to a serialized version of params?
