### ISSUE TITLE
Can't handle the charset attribute in a Content-Type header

### ISSUE THREAD

**Issue by SaberStrat** [loadimpact/har-to-k6#15]
**How to reproduce:**
Run
```
fetch('http://example.com', {
      method: 'POST',
      headers: new Headers({
               'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
               }),
		body: 'foo0=bar0&foo1=bar1'
    })
    .then(res => res.json())
    .then(console.log)
```
in Chrome v78.0.3904.97 DevTools Console and Save Content as HAR the Network Tab.
Trying to convert it using the har-to-k6 converter results in the error
```InvalidPostDataType: Invalid structured post data MIME type (0): application/x-www-form-urlencoded; charset=UTF-8```

**Problem:**
HAR 1.2 specification doesn't explicitly exclude charset attributes in the mimeType in the postData of requests. But since Chrome puts the `content-type` header in the mimeType too, it should be supported by the converter too.

**Comment by simskij** [comment]
Solved in #22
