### ISSUE TITLE
Missing page title (0) error

### ISSUE THREAD

**Issue by na--** [loadimpact/har-to-k6#16]
I was trying to convert this very simple HAR file: [test.loadimpact.com_Archive [19-12-13 12-52-20].har.txt](https://github.com/loadimpact/har-to-k6/files/3960420/test.loadimpact.com_Archive.19-12-13.12-52-20.har.txt)

And this is what I got:
```
% npx har-to-k6 test.loadimpact.com_Archive\ \[19-12-13\ 12-52-20\].har 
Converting 'test.loadimpact.com_Archive [19-12-13 12-52-20].har'
Error converting archive:
Missing page title (0)
```

**Comment by MStoykov** [comment]
How did you create this har file?

**Comment by na--** [comment]
Simply by going to http://test.loadimpact.com with Firefox and saving the requests from the Network tab as a HAR file.
