### ISSUE TITLE
Post data conflict: params and text must be equal if both are provided

### ISSUE THREAD

**Issue by clem4962** [loadimpact/har-to-k6#50]
When POST data contains both "params" and "text", there is a check for their equivalence in validate/postData.js

This fails when escaped characters exist in the text data, as below.

Problem can be worked around by removing the check (does it have any purpose?)

            "params": [
              {
                "name": "page",
                "value": "SandBox"
              },
              {
                "name": "wikimarkup",
                "value": "line 1"
              }
            ],
            "text": "page=SandBox&wikimarkup=line%201"

Output from hacked version of code, having added this to error block:

      console.log(seralizeURLSearchParams(node.params))
      console.log(node.text)

har-to-k6 buggy.har -o buggy.js
Converting 'buggy.har'
page=SandBox&wikimarkup=line 1
page=SandBox&wikimarkup=line%201
Error converting archive:
Post data conflict (0): params and text must be equal if both are provided

[buggy.har.gz](https://github.com/loadimpact/har-to-k6/files/5096374/buggy.har.gz)

**Comment by allansson** [comment]
This issue has been fixed in https://github.com/loadimpact/har-to-k6/pull/45. It will be released in the next version, probably later this week.
