### ISSUE TITLE
har generated from chrome produces: "Missing request method (24)"

### ISSUE THREAD

**Issue by tmc** [loadimpact/har-to-k6#63]
```
        "request": {
          "method": "",
          "url": "ws://localhost:2992/sockjs-node/248/gp0g1n1n/websocket",
          "httpVersion": "",
          "headers": [],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
```

**Comment by legander** [comment]
Thank you for reporting the issue. There is currently no support for compiling "websocket requests" (Yet).
I'm adding a `Type: Improvement` label 👍

**Comment by legander** [comment]
Closing this issue in favor of https://github.com/loadimpact/har-to-k6/issues/47. We will look into adding WS support in the future 👍

**Comment by BradErz** [comment]
@legander would it not make sense for now to output a warning that a specific URL has no method and skip generating the code for the websocket as its not supported yet?

**Comment by legander** [comment]
@BradErz That is a good idea, I will add a reference to your suggestion in #47 👍
